#ifndef CIRCUIT_CONFIG_H
#define CIRCUIT_CONFIG_H
//TODO FIX CONFIRM ALL PINS
///Connected Pins
#define CHARGE_DISCHARGE_RELAY_PIN 12
#define SAFETY_RELAY_PIN 13
#define PWM_PIN_CHARGE 9
#define PWM_PIN_DISCHARGE 8
//CIRCUIT SAFETY

#define MAX_VOLTAGE 4.2
#define MIN_VOLTAGE 3.0
#define MAX_CURRENT 5.0 
#define MIN_CURRENT -5.0
#define MAX_TEMPERATURE 60.0
#define MIN_TEMPERATURE 20.0
#define MAX_STOPTIME 200
#define MIN_STOPTIME 0
//TIMES IN SECONDS
#define MAX_PULSE_ON_TIME_S 600
#define MIN_PULSE_ON_TIME_S 0
#define MAX_PULSE_OFF_TIME_S 600
#define MIN_PULSE_OFF_TIME_S 0
//////////////////////////CIRCUIT DEFAULT PARAMS
#define DEFAULT_STOPTIME (MIN_STOPTIME+((MAX_STOPTIME-MIN_STOPTIME)/2))
#define DEFAULT_VOLTAGE (MIN_VOLTAGE+((MAX_VOLTAGE-MIN_VOLTAGE)/2))
#define DEFAULT_CURRENT (MIN_CURRENT+((MAX_CURRENT-MIN_CURRENT)/2))

#define DEFAULT_PULSE_ON_TIME_S (MIN_PULSE_ON_TIME_S+((MAX_PULSE_ON_TIME_S-MIN_PULSE_ON_TIME_S)/2))
#define DEFAULT_PULSE_OFF_TIME_S (MIN_PULSE_OFF_TIME_S+((MAX_PULSE_OFF_TIME_S-MIN_PULSE_OFF_TIME_S)/2))

//BLUETOOTH PARAMS
//////////////////////// Your custom BLE UUIDs Paired with your App
#define SERVICE_UUID "58f4c711-037d-4dd5-8b2c-80a46b3d9ab4"
#define CHARACTERISTIC_UUID "31c9dd7b-e55d-4e99-8b8a-e7a00857949a"
////////////////////////
#define VOLTAGE_DIVIDER_FACTOR 2
#endif